In [27]:
import keras
from keras.layers import Dense,Conv2D,MaxPool2D,Activation, Dropout, Flatten, Dense,BatchNormalization
from keras.models import Sequential
from keras.optimizers import RMSprop
import pandas as pd
train = pd.read_csv("../input/train.csv")
Y_train=train["label"]
X_train=train.drop(labels = ["label"],axis = 1)
X_train /= 255
Y_train = keras.utils.to_categorical(Y_train, 10)
print(X_train.shape)
print(Y_train.shape)
X_train = X_train.values.reshape(42000, 28,28, 1)
print(X_train.shape)


(42000, 784)
(42000, 10)
(42000, 28, 28, 1)


In [28]:
model = Sequential()
model.add(Conv2D(input_shape=(28,28,1),filters = 32, kernel_size = (5,5),activation ='relu'))
model.add(MaxPool2D(pool_size=(2,2)))
model.add(Conv2D(filters = 32, kernel_size = (5,5),activation ='relu'))
model.add(MaxPool2D(pool_size=(2,2)))
model.add(Conv2D(filters = 32, kernel_size = (3,3),activation ='relu'))
model.add(Flatten())
model.add(Dense(128,activation='relu'))
model.add(Dropout(0.25))
model.add(Dense(10,activation='softmax'))

In [29]:
model.compile(loss='categorical_crossentropy',
optimizer=RMSprop(0.001),
metrics=['accuracy'])  

In [30]:
model.fit(X_train,Y_train, batch_size=32, epochs=20, verbose=1, validation_split=0.2)

Train on 33600 samples, validate on 8400 samples
Epoch 1/20
33600/33600 [==============================] - 9s 275us/step - loss: 0.2588 - acc: 0.9187 - val_loss: 0.0653 - val_acc: 0.9768
Epoch 2/20
33600/33600 [==============================] - 9s 257us/step - loss: 0.0748 - acc: 0.9773 - val_loss: 0.0554 - val_acc: 0.9851
Epoch 3/20
33600/33600 [==============================] - 9s 270us/step - loss: 0.0499 - acc: 0.9848 - val_loss: 0.0418 - val_acc: 0.9888
Epoch 4/20
33600/33600 [==============================] - 9s 269us/step - loss: 0.0397 - acc: 0.9877 - val_loss: 0.0590 - val_acc: 0.9856
Epoch 5/20
33600/33600 [==============================] - 9s 265us/step - loss: 0.0315 - acc: 0.9906 - val_loss: 0.0432 - val_acc: 0.9875
Epoch 6/20
33600/33600 [==============================] - 9s 261us/step - loss: 0.0286 - acc: 0.9915 - val_loss: 0.0446 - val_acc: 0.9902
Epoch 7/20
33600/33600 [==============================] - 9s 256us/step - loss: 0.0244 - acc: 0.9931 - val_loss: 0.0625 - v

In [31]:
test=pd.read_csv('../input/test.csv')

test=test.values.reshape(28000,28,28,1)
predict=model.predict(test)
print(predict)
accuracy = model.evaluate(X_train,Y_train,batch_size=32)
print("Accuracy: ",accuracy[1])




[[0. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 1.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 1. ... 0. 0. 0.]]
42000/42000 [==============================] - 3s 82us/step
Accuracy:  0.9974761904761905


In [32]:
predict = model.predict_classes(test, verbose=1)

28000/28000 [==============================] - 2s 69us/step


In [33]:
data_predictions = pd.DataFrame({"ImageId": list(range(1,len(predict)+1)),"Label": predict})
data_predictions.to_csv('predictions.csv', index=False, header=True)
print(data_predictions)

       ImageId  Label
0            1      2
1            2      0
2            3      9
3            4      0
4            5      3
5            6      7
6            7      0
7            8      3
8            9      0
9           10      3
10          11      5
11          12      7
12          13      4
13          14      0
14          15      4
15          16      5
16          17      3
17          18      1
18          19      9
19          20      0
20          21      9
21          22      1
22          23      1
23          24      5
24          25      7
25          26      4
26          27      2
27          28      7
28          29      4
29          30      7
...        ...    ...
27970    27971      5
27971    27972      0
27972    27973      4
27973    27974      8
27974    27975      0
27975    27976      3
27976    27977      6
27977    27978      0
27978    27979      1
27979    27980      9
27980    27981      3
27981    27982      1
27982    27983      1
27983    2